In [2]:
import cv2
import numpy as np

In [29]:
#imread is the function to read the images. It takes the path of the image present in the disk
img = cv2.imread('../data set/3143130.jpg')

In [30]:
# imshow is the function to display the image. It takes 2 arguements
# first arguements is the name of the outputwindow
# second argument is the image which needs to be displayed
cv2.imshow("output1",img)

# if we dont add the add, it closes very quick. if we add a parameter 0 it means infinte time 
cv2.waitKey(0)
cv2.destroyAllWindows()

In [31]:
# Videocapture is the function to read the videos from the disk
cap = cv2.VideoCapture('../data set/AundhBridge.mp4')

In [32]:
# since video is series of frames we need to display the video using the while loop
while True:
    # here we are reading the video frame by frame. each frame is stored in img
    # sucess is boolean flag which tells whether the image is sucessfully read or not
    success, img2 = cap.read()
    # here we display the single frame which is stores in the variable img
    # video is the window name
    cv2.imshow('video',img2)
    # here if the delay is one milli second and q key is pressed then we stop the
    # window and close the video
    if cv2.waitKey(1) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break
    

In [33]:
# now we read the video from the webcam. 
# the id of the webcam needs to send as a parameter 
# if we send 0 the default web cam will be read from 
cap1 = cv2.VideoCapture(0)

# we can the set the height and width of the video
# 3 is the id to set the width
# 4 is the id to set the height
# 10 is the id to set the brightness
cap1.set(3,640)
cap1.set(4,480)
cap1.set(10, 100)

True

In [34]:
# since video is series of frames we need to display the video using the while loop
while True:
    # here we are reading the video frame by frame. each frame is stored in img
    # sucess is boolean flag which tells whether the image is sucessfully read or not
    success, img1 = cap1.read()
    # here we display the single frame which is stores in the variable img
    # video is the window name
    cv2.imshow('video',img1)
    # here if the delay is one milli second and q key is pressed then we stop the
    # window and close the video
    if cv2.waitKey(1) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break
    

# HOW TO CONVERT IMAGE TO GRAY SCALE 

In [37]:
#  now we will work with the images basic function
# here we are converting the image to grey scale image
# cvtColor convert the image into respective colour space
# in opencv the color is in BGR format 
# to convert to gray we need to use cv2.COLOR_BAYER_BGR2GREY color space
imgGray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow('Color',img)
cv2.imshow('Gray Image',imgGray)
cv2.waitKey(0)
cv2.destroyAllWindows()

#  HOW TO BLUR THE IMAGE 

In [38]:
# here we will use the gausscian blur image to blur our image 
# GaussianBlur is the function used
# it takes 3 paramters
# first one is the image
# second is the kernel size perferable a odd number size of matrix
# third is the sigmaX value
imageBlur = cv2.GaussianBlur(imgGray, (7,7),0)
cv2.imshow('Blur Image',imageBlur)
cv2.imshow('Color',img)
cv2.imshow('Gray Image',imgGray)
cv2.waitKey(0)
cv2.destroyAllWindows()

# HOW TO DETECT THE EDGES USING KANNY EDGE DETECTOR 

In [39]:
# here we will be using kanny edge detection
# it takes 3 parameters
# first parameter is the image
# second parameter is the threshold1
# third paramter is the threshhold
imgCanny = cv2.Canny(img, 150, 200)

cv2.imshow('Blur Image',imageBlur)
cv2.imshow('Color',img)
cv2.imshow('Gray Image',imgGray)
cv2.imshow('Canny Image',imgCanny)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Dilation

In [40]:
# now while detecting the edges the lines are not complete. 
# to complete those lines we have the concept of dilation( it also increases the 
#thicknes of the line)
# dilate function does the dilation process which takes 3 paramters
# the first paramter is images. here we are talking about the images edges hence 
# second paramter is the kernel matrix 
# third paramter is the number of iterations. i.e., the thickness of the edges
kernel = np.ones((5,5), np.uint8)
imgDilation = cv2.dilate(imgCanny,kernel, iterations =1)

cv2.imshow('Blur Image',imageBlur)
cv2.imshow('Color',img)
cv2.imshow('Gray Image',imgGray)
cv2.imshow('Canny Image',imgCanny)
cv2.imshow('Dilation Image',imgDilation)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Erosion (the opposite of dilation)

In [41]:
# erode function does the erosion process which takes 3 paramters
# the first paramter is images. here we are talking about the images edges hence 
# second paramter is the kernel matrix 
# third paramter is the number of iterations. i.e., the thickness of the edges
imgEroded = cv2.erode(imgDilation, kernel, iterations =1)

cv2.imshow('Blur Image',imageBlur)
cv2.imshow('Color',img)
cv2.imshow('Gray Image',imgGray)
cv2.imshow('Canny Image',imgCanny)
cv2.imshow('Dilation Image',imgDilation)
cv2.imshow('Eroded Image',imgEroded)
cv2.waitKey(0)
cv2.destroyAllWindows()

# We will look about resizing and cropping of the images 

In [42]:
# for resizing of the image first we need to know about the shape of the image 
print(img.shape)

# here 373 is the height and 636 is the width of the image and 3 is 3 channels

(373, 636, 3)


In [46]:
# now we will resize the image 
# resize is the function which takes 2 paramets
# first paramter is the image 
# second is the new size (width, height)
imgResize = cv2.resize(img, (300, 150))
print(imgResize.shape)
cv2.imshow("output1",img)
cv2.imshow("Re sized Image",imgResize)

cv2.waitKey(0)
cv2.destroyAllWindows()

(150, 300, 3)



# Cropping of the image 

In [45]:
# for cropping an image we can use the simple matrix calculations 
# the first would be the height and second would be the width
imgCropped = img[0:200,200:500]
cv2.imshow("output1",img)
cv2.imshow("Cropped Image",imgCropped)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Shapes and Texts

In [77]:
# here we will try to draw lines triangles rectangles and circle on the image 
# also learn how to put text on images
# first we will create a matrix with zeros using numpy. zero means black. One means white
# here 3 is the channels
imgblack = np.zeros((512,512,3), np.uint8)
cv2.imshow("Image1",imgblack)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(imgblack.shape)

(512, 512, 3)


In [78]:
# now we will look how can we color this image
# here we are completely colouring the image. We have coloured the whole image with blue
# colon here refers to all values in the matrix
imgblack[:] = 255,0,0
cv2.imshow("Image2",imgblack)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [79]:
# now we will look how can we color this image
# here we are  colouring part the image. We have coloured the whole image with blue
# colon here refers to all values in the matrix
imgblack[200:300,100:300] = 0,255,0
print(imgblack)
cv2.imshow("Image3",imgblack)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 ...

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]]


In [80]:
# lets now learn about how to draw lines on the images
# line function takes  5 paramters
# first parmater is the image
# second paramter is the starting point
# third parameter is the ending point
# fourth paramter is the colour of the line
# fifth paramter is the thickness os the line
cv2.line(imgblack, (0,0), (300,300), (0,0,255), 3)
cv2.imshow("Image4",imgblack)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [81]:
# lets now learn about how to draw rectangles on the images
# rectangle function takes 5 paramters
# first parmater is the image 
# second paramter is the starting point (diagnol starting point)
# third parameter is the ending point (diagnol ending point)
# fourth paramter is the colour of the line
# fifth paramter is the thickness os the line
cv2.rectangle(imgblack, (0,0), (250,350), (100,125,255), 3)
cv2.imshow("Image5",imgblack)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [82]:
# lets now learn about how to draw rectangles and fill the rectangle on the images
# rectangle function takes 5 paramters
# first parmater is the image 
# second paramter is the starting point (diagnol starting point)
# third parameter is the ending point (diagnol ending point)
# fourth paramter is the colour of the line
# fifth paramter is the parameter to say to be filled
cv2.rectangle(imgblack, (0,0), (250,350), (100,125,255), cv2.FILLED)
cv2.imshow("Image6",imgblack)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [83]:
# lets now learn about how to draw circles on the images
# circle function takes 5 paramters
# first parmater is the image 
# second paramter is the center of the circle
# third parameter is the radius of the circle
# fourth paramter is the colour of the line
# fifth paramter is the thickness
cv2.circle(imgblack, (400,50), 30, (55,75,255), 5)
cv2.imshow("Image7",imgblack)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [84]:
# now we will learn how to put the text on the image 
# putText takes 
# first parmater is the image
# second paramter what text we should be displaying
# third paramter is the origin of the text
# fourth paramter is the font 
# fifth paramter is the scale
# sixth paramter is the color 
# seventh paramter is the thickness of the text
cv2.putText(imgblack, 'Hello OpenCV', (100,100), cv2.FONT_HERSHEY_COMPLEX,1,(0,150,0,2))
cv2.imshow("Image8",imgblack)
cv2.waitKey(0)
cv2.destroyAllWindows()

# WRAP PRESPECTIVE

In [11]:
# now we learning about the wrap prespective of an image 
# we will try to get the single image of cards. we need the four points of the image 
# in the four points we are going to apply the wrap prespective

width,height = 250,350
img123 = cv2.imread('../data set/cards.jpg')
# four corner points of the image  
pts1 = np.float32([[529,142],[771,190],[405,395],[674,457]])
# now for each point we need mention which corner are we refering to 
pts2 = np.float32([[0,0],[width,0],[0,height],[width, height]])

# now we write the tranformation matrix using getPrespectiveTranform
# 2 paramters the points 
matrix = cv2.getPerspectiveTransform(pts1, pts2)

imgoutput = cv2.warpPerspective(img123, matrix, (width, height))
cv2.imshow("Image9",img123)
cv2.imshow("Image10",imgoutput)
cv2.waitKey(0)
cv2.destroyAllWindows()

# JOINING IMAGES

In [12]:
# we will now try to stack the images vertical and horizonal using numpy 
# this can be achived if we have the same shape and same channel

img111 = cv2.imread('../data set/3143130.jpg')

imghor = np.hstack((img111,img111))
imgver = np.vstack((img111, img111))

cv2.imshow("Image11",imghor)
cv2.imshow("Image12",imgver)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
# now we write a custom function to stack the images 

def stackImages(scale,imgArray):
    rows = len(imgArray)
    cols = len(imgArray[0])
    rowsAvailable = isinstance(imgArray[0], list)
    width = imgArray[0][0].shape[1]
    height = imgArray[0][0].shape[0]
    if rowsAvailable:
        for x in range ( 0, rows):
            for y in range(0, cols):
                if imgArray[x][y].shape[:2] == imgArray[0][0].shape [:2]:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (0, 0), None, scale, scale)
                else:
                    imgArray[x][y] = cv2.resize(imgArray[x][y], (imgArray[0][0].shape[1], imgArray[0][0].shape[0]), None, scale, scale)
                if len(imgArray[x][y].shape) == 2: imgArray[x][y]= cv2.cvtColor( imgArray[x][y], cv2.COLOR_GRAY2BGR)
        imageBlank = np.zeros((height, width, 3), np.uint8)
        hor = [imageBlank]*rows
        hor_con = [imageBlank]*rows
        for x in range(0, rows):
            hor[x] = np.hstack(imgArray[x])
        ver = np.vstack(hor)
    else:
        for x in range(0, rows):
            if imgArray[x].shape[:2] == imgArray[0].shape[:2]:
                imgArray[x] = cv2.resize(imgArray[x], (0, 0), None, scale, scale)
            else:
                imgArray[x] = cv2.resize(imgArray[x], (imgArray[0].shape[1], imgArray[0].shape[0]), None,scale, scale)
            if len(imgArray[x].shape) == 2: imgArray[x] = cv2.cvtColor(imgArray[x], cv2.COLOR_GRAY2BGR)
        hor= np.hstack(imgArray)
        ver = hor
    return ver

img11 = cv2.imread('../data set/3143130.jpg')
img121 = cv2.cvtColor(img11, cv2.COLOR_BGR2GRAY)

imgstack = stackImages(0.75,([img11, img121, img11],[img121, img11, img121]))
cv2.imshow("Image13",imgstack)
cv2.waitKey(0)
cv2.destroyAllWindows()

# COLOR DETECTION